blog/urls.py
from django.urls import path,re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.ArticleListView.as_view(),name='article_list'),
    re_path(r'^article/create/$',views.ArticleCreateView.as_view(), name='article_create'),
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/$',views.ArticleDetailView.as_view(),name='article_detail'),
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/update/$',views.ArticleUpdateView.as_view(),name='article_update'),
    re_path(r'^tag/add/$',views.TagCreate,name='tag_add'),
    re_path(r'^category/add/$',views.CategoryCreate,name='category_add'),
]

myaccount/urls.py
from django.urls import re_path
from . import views

app_name = "myaccount"
urlpatterns = [
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^login/$',views.login,name='login'),
    re_path(r'^user/profile/$',views.profile,name='profile'),
    re_path(r'^user/profile/update/$',views.profile_update,name='profile_update'),
    re_path(r'^user/(?P<pk>\d+)/pwdchange/$',views.pwd_change,name='pwd_change'),
    re_path(r'^logout/$',views.logout,name='logout'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('myaccount.urls')),
    path('',include('blog.urls')),
]

blog/models.py
import datetime

import unidecode as unidecode
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.template.defaultfilters import slugify
from django.urls import reverse


class Article(models.Model):

    STATUS_CHOICES = (
        ('d','草稿'),
        ('p','发表'),
    )

    title = models.CharField('标题',max_length=200,unique=True)
    #Django中的Slug会为每条model记录，自动（当然可以手动）的根据当前记录的每个字段的Value生成一个URL路径（唯一的），
    # 使得你的URL更加的易读（或者也能规避一些额外的问题）
    slug = models.SlugField('slug',max_length=60,blank=True)
    body = models.TextField('正文')
    summary = models.CharField(max_length=200,blank=True,verbose_name="博客摘要")
    pub_date = models.DateTimeField('发布时间',null=True)
    create_date = models.DateTimeField('创建时间',auto_now_add=True) #添加时的时间，更新对象不会有变动
    mod_date = models.DateTimeField('修改时间',auto_now=True) #有修改动作，就会变
    status = models.CharField('文章状态',max_length=1,choices=STATUS_CHOICES,default='p')
    views = models.PositiveIntegerField('浏览量',default=0)
    author = models.ForeignKey(User,verbose_name='作者',on_delete=models.CASCADE)
    category = models.ForeignKey('Category',verbose_name='分类',on_delete=models.CASCADE,blank=False,null=False)
    tags = models.ManyToManyField('Tag',verbose_name='标签集合',blank=True)

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(unidecode.unidecode(self.title))

        self.summary = self.body[:60]
        super().save(*args,**kwargs)



    def clean(self):
        if self.status == 'd' and self.pub_date is not None:
            self.pub_date = None
        if self.status == 'p' and self.pub_date is None:
            self.pub_date = datetime.datetime.now()

    def get_absolute_url(self):
        return reverse('blog:article_detail',args=[str(self.pk),self.slug])

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def published(self):
        self.status = 'p'
        self.pub_date = datetime.datetime.now()
        self.save(update_fields=['status','pub_date'])

    class Meta:
        ordering = ['-pub_date']    ## 按降序排列，-表示降序
        verbose_name = "文章"
        verbose_name_plural = verbose_name   ##复数形式

class Category(models.Model):
    name = models.CharField('分类名',max_length=30,unique=True)
    slug = models.SlugField('slug',max_length=40)
    parent_category = models.ForeignKey('self',verbose_name="父级分类",blank=True,null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category_detail',args=[self.slug])

    def has_child(self):
        if self.category_set.all().count() > 0:
            return True



    def save(self,*args,**kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(unidecode.unidecode(self.name))

        super().save(*args,**kwargs)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

class Tag(models.Model):
    name = models.CharField('标签名',max_length=30,unique=True)
    slug = models.SlugField('slug',max_length=40)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail',args=[self.slug])

    def get_article_count(self):
        return Article.objects.filter(tags__slug=self.slug).count()

    def save(self,*args,**kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(unidecode.unidecode(self.name))

        super().save(*args,**kwargs)

blog/forms.py
from django import forms
from .models import Article, Tag, Category

# 定制forms部件widget
# 　　Django 会把部件渲染成 HTML，这个渲染过程只会执行最小的工作量 -- 不会添加类名，或者其它具体的属性。这意味着，例如，所有 TextInput 部件会在你所有的Web页面上具有一样的外观。
# 　　有两种办法可以订制部件：一是定制部件的实例对象（订制 field 属性）；二是继承部件，定义内部类（订制 css 和 js 文件的链接）。

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ['author','views','slug','pub_date','summary']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        exclude = ['slug']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

CATEGORY = Category.objects.all()

class CategoryForm(forms.Form):
    name = forms.CharField()
    parent_category = forms.ModelChoiceField(queryset=CATEGORY)

#此 form 包含三个默认的 TextInput 部件，默认没有 CSS 类渲染，没有额外的属性。这意味着每个部件会具有同样的外观。


#form类所做的就是第一步就是快速生成html代码
#数据校验与错误信息提示
# f=ContactForm({'name':'BeginMan','age':100,'email':'x@163.com'})
# >>> f.is_bound    #一旦你对一个Form实体赋值，你就得到了一个绑定form
# True
# >>> f.is_valid()    #调用任何绑定form的is_valid()方法，就可以知道它的数据是否合法
# True
# >>> f = ContactForm({'name':'BeginMan'})
# >>> f.is_valid()
# False

#每一个邦定Form实体都有一个errors属性，它提供了一个字段与错误消息相映射的字典表。
# >>> f.errors
# {'age': [u'This field is required.']}
# >>> f.errors['age']
# [u'This field is required.']
# >>> f['age'].errors
# [u'This field is required.']

# 如果form对象的数据合法，则有cleaned_data属性，一个清理过的提交数据字典。
# 当通过一系列的数据来创建表单对象，并验证通过的时候，就要使用cleaned_data属性进行‘清理工作’，所谓的清理就是对给定的数据对应到python类型。
#
# >>> f.cleaned_data
# {'age': 100, 'name': u'BeginMan', 'email': u'x@163.com'}

# if request.method == 'POST':
#         form = ContactForm(request.POST)    #绑定post数据
#         ....
#  else:
#         form = ContactForm()  #如果表单未被提交，则一个未绑定的表单实例被创建

# Form.initial表单初始化。
#
# 我认为就是给表单绑定一些数据，用于特定显示或处理。当然这些可有可无，如提示等。如果提供，则是包含表单字段的字典类型。如：
#
# f = ContactForm(initial={'name':'Hi,here','email':'@'})
# 可以在表单类中初始化，也可以在表单对象中初始化，对于同一个字段的初始化，后者覆盖前者。

blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin

from blog.forms import ArticleForm, TagForm, CategoryForm
from blog.models import Article, Tag, Category
from comments.forms import CommentForm
from comments.models import Comment


class ArticleListView(ListView):  #当我们使用Django自带的ListView展示所有对象列表时，ListView默认会返回Model.objects.all()。
    template_name = "blog/published_article_list.html"
    paginate_by = 3

    def get_queryset(self):
        return Article.objects.filter(status='p').order_by('-pub_date')

@method_decorator(login_required,name='dispatch')
class PublishedArticleListView(ListView):
    template_name = "blog/published_article_list.html"
    paginate_by = 3

    def get_queryset(self):     #可以通过更具体的get_queryset方法来返回一个我们想要显示的对象列表。
        return Article.objects.filter(author=self.request.user).filter(status='p').order_by('-pub_date')

@method_decorator(login_required,name='dispatch')
class ArticleDraftListView(ListView):
    template_name = "blog/published_article_list.html"
    paginate_by = 3

    def get_queryset(self):
        return Article.objects.filter(author=self.request.user).filter(status='d').order_by('-pub_date')


class ArticleDetailView(FormMixin,DetailView): # DetailView和EditView都是从URL根据pk或其它参数调取一个对象来进行后续操作。
    model = Article
    template_name = "blog/article_detail.html"
    form_class = CommentForm

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.viewed()                                          #
        return obj

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView,self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'article':self.object})
        context['comments'] = self.object.comment_set.all()
        return context

    def get_success_url(self):
        return reverse('blog:article_detail',kwargs={'pk':self.object.pk,'slug1':self.object.slug})


    def post(self,request,*args,**kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if request.user.id == None:
            return HttpResponseRedirect(reverse('myaccount:login'))
        if form.is_valid():
            comment = Comment(user=request.user,text=form.cleaned_data['text'],article=self.object,reply_id=form.cleaned_data.get('reply_id',0),reply_user=form.cleaned_data.get('reply_user',''))
            return self.form_valid(comment)


    def form_valid(self, comment):
        comment.save()
        return super(ArticleDetailView,self).form_valid(comment)



#     源码：
#         def get_success_url(self):
#         """Return the URL to redirect to after processing a valid form."""
#         if not self.success_url:
#             raise ImproperlyConfigured("No URL to redirect to. Provide a success_url.")
#         return str(self.success_url)  # success_url may be lazy
#
#     def form_valid(self, form):
#         """If the form is valid, redirect to the supplied URL."""
#         return HttpResponseRedirect(self.get_success_url())
#
#     def form_invalid(self, form):
#         """If the form is invalid, render the invalid form."""
#         return self.render_to_response(self.get_context_data(form=form))







@method_decorator(login_required,name='dispatch')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/article_create_form.html'

    def form_valid(self, form):                             #
        form.instance.author = self.request.user
        return super().form_valid(form)



@method_decorator(login_required,name='dispatch')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/article_update_form.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.author !=self.request.user:
            raise Http404()
        return obj

@method_decorator(login_required,name='dispatch')
class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:article_list')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.author != self.request.user:
            raise Http404()
        return obj

@method_decorator(login_required,name='dispatch')
def article_publish(request,pk,slug1):
    article = get_object_or_404(Article,pk=pk,author=request.user)
    article.published()




@login_required
def TagCreate(request):
    tag = Tag.objects.all()
    form = TagForm
    if request.method == 'POST':
        form = TagForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse("blog:tag_add"))

    return render(request,'blog/tag_create_form.html',{'tag':tag,'form':form})


@login_required
def CategoryCreate(request):
    if request.method == 'GET':
        category = Category.objects.all()
        form = CategoryForm()
        return render(request, 'blog/category_create_form.html', {'category': category, 'form': form})
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            parent_category = form.cleaned_data['parent_category']
            Category(name=name,parent_category=parent_category).save()
            return HttpResponseRedirect(reverse("blog:category_add"))

blog/templates/blog/article_create_form.html
{% extends 'blog/base.html' %}

{% block main %}
<main style="display:flex;justify-content:center;">

    <form method="post" class="form-horizontal" role="form" action="">

    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}

    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger col-md-12" role="alert">

    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
    </div>

    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group col-md-12">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}
                 <div class="invalid-feedback">
              {{ error }}
            </div>
            {% endfor %}
        {% endif %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    </div>
    {% endfor %}



    <div class="form-group">
     <div class="col-md-12">
    <input type="submit" class="btn btn-primary form-control" value="提交">
     </div>
  </div>

    </form>
</main>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends "blog/base.html" %}

{% block main %}
 <article class="post post-1">
        <header class="entry-header">
            <h1 class="text-left">{{ article.title }}{% if article.status == 'd' %}(草稿){% endif %}</h1>

            <div class="text-left">
            {% if article.status == "p" %}
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ article.create_date }}">{{ article.create_date }}</time></a></span>
            {% endif %}


                <span class="post-author"><a href="#">{{ article.author }}</a></span>
                <span class="comments-link"><a href="#">4 评论</a></span>
                <span class="views-count"><a href="#">{{ article.views }} 阅读</a></span>
                            <span class="post-category">{% if article.category.parent_category %}
    <a href="#">{{ article.category.parent_category.name }}</a>
    {% endif %}
    <a href="#">{{ article.category }}</a></span>
                         {% for tag in article.tags.all %}
            <a href="#">{{ tag.name }}</a>
        {% endfor %}
                {% if article.author == request.user %}
            {% if article.status == "d" %}
            <a href="#">发布</a> |
            {% elif article.status == "p" %}
                <a href="{% url 'blog:article_update' article.id article.slug %}">编辑</a> |
        <a href="#">删除</a>
            {% endif %}
                    {% else %}
                    <p></p>
        {% endif %}
            </div>
               <hr>
        </header>
        <div class="entry-content clearfix">

            {#  /*告诉html， 里面变量的字符串是安全的， 不需要进行转义*/#}
           {{ article.body | safe }}

        </div>
    </article>




     <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="#" method="post" class="comment-form">
            <div class="row">
                <div class="col-md-4">
                    {% csrf_token %}
                    <label for="id_name">{{ form.user.label }}</label>
                </div>

                <div class="col-md-12">
                    <label for="id_comment">{{ form.text.label }}</label>
                    {{ form.text }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>4</span> 条评论</h3>
            <ul class="comment-list list-unstyled">

                {% for comment in comments %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.user }}</span>
                                <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                                <a class="pull-right reply_btn" href="#" >回复</a>
                            </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

blog/templates/blog/article_update_form.html
{% extends 'blog/base.html' %}

{% block main %}


    <form method="post" class="form-horizontal" role="form" action="">

    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}

    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger col-md-12" role="alert">

    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
    </div>

    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group col-md-12">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}
                 <div class="invalid-feedback">
              {{ error }}
            </div>
            {% endfor %}
        {% endif %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    </div>
    {% endfor %}
    <div class="form-group">
     <div class="col-md-12">
    <input type="submit" class="btn btn-primary form-control" value="提交">
     </div>
  </div>

    </form>

{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>myBlog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">
{#添加高亮显示的css样式, 也可以选择其他的样式#}
    <link rel="stylesheet" href="/static/css/highlights/emacs.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url 'blog:article_list' %}">博客首页</a>
{#          <div class="nav-collapse collapse">#}
            <ul class="nav">
              <li ><a href="{% url 'myaccount:profile' %}">个人空间</a></li>
              <li><a href="{% url 'blog:article_create' %}">写博客</a></li>
              <li><a href="#">联系</a></li>

            </ul>
                {% if request.user.id  is  None %}
                    <a class="btn btn-info" style="float: right;" href="{% url 'myaccount:register' %}">注册</a>
                    <a  class="btn btn-success" style="float: right;" href="{% url 'myaccount:login' %}">登录</a>

                {% else %}
                 <a  class="btn btn-primary" style="float: right;" href="{% url 'myaccount:logout' %}">注销</a>
                {% endif %}
{#          </div><!--/.nav-collapse -->#}
        </div>
      </div>
    </div>

    <div class="content-body">
    <div class="container">
        <div class="row">

    {% block main %}



    {% endblock %}
            </main>
        </div>
    </div>
    </div>



  </body>
</html>

blog/templates/blog/category_create_form.html
{% extends 'blog/base.html' %}

{% block main %}

    {% for i in category %}
    <p>{{ i.name }}</p>

    {% endfor %}

 <form method="post" class="form-horizontal" role="form" action="">

    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}

    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger col-md-12" role="alert">

    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
    </div>

    {% endif %}

    {% for field in form %}
    <div class="form-group col-md-12">
        {{ field }}
    </div>
    {% endfor %}
{#       <div class="form-group col-md-12">#}
{#        {{ field.label_tag }}#}
{#        {{ field.parent_category }}#}
{#        {% if field.errors %}#}
{#            {% for error in field.errors %}#}
{#                 <div class="invalid-feedback">#}
{#              {{ error }}#}
{#            </div>#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#        <small class="form-text text-muted">{{ field.help_text }}</small>#}
{#    </div>#}

    <div class="form-group">
     <div class="col-md-12">
    <input type="submit" class="btn btn-primary form-control" value="提交">
     </div>
  </div>

    </form>


{% endblock %}

blog/templates/blog/published_article_list.html
{% extends 'blog/base.html' %}


{% block main %}
<main class="center">

{#    <form action="{% url 'blog:article_search' %}" role="search" method="get">#}
{#    {% csrf_token %}#}
{#    <div class="input-group col-md-12">#}
{#        <input type="text" name="q" id="q" class="form-control" placeholder="搜索文章">#}
{#        <span class="input-group-btn">#}
{#            <button class="btn btn-default form-control" type="submit" value="submit">#}
{#                <span class="glyphicon glyphicon-search"></span>#}
{#            </button>#}
{#        </span>#}
{#    </div>#}
{#    </form>#}
{#    page_obj:当前的page对象#}
    {% if page_obj %}

            {% for  post in page_obj %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{% url 'blog:article_detail' post.id post.slug %}">{{ post.title }}</a>
                </h1>
 <p>{{ post.summary }}</p>
                <div class="entry-meta">

                    <span class="post-category"><a href="#">{{ post.category }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.create_date }}">{{ post.create_date }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">4 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
{#                <p>{{ post.summary }}</p>#}
                <div class="read-more cl-effect-14">
                    <a href="{% url 'blog:article_detail' post.id post.slug %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
            {% endfor %}
        {% endif %}




    {% if is_paginated %}
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a> </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                     <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a> </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
        </ul>
    {% endif %}

</main>
{% endblock %}

blog/templates/blog/tag_create_form.html
{% extends 'blog/base.html' %}

{% block main %}

    {% for i in tag %}
    <p>{{ i.name }}</p>

    {% endfor %}

 <form method="post" class="form-horizontal" role="form" action="">

    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}

    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger col-md-12" role="alert">

    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
    </div>

    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group col-md-12">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}
                 <div class="invalid-feedback">
              {{ error }}
            </div>
            {% endfor %}
        {% endif %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    </div>
    {% endfor %}
    <div class="form-group">
     <div class="col-md-12">
    <input type="submit" class="btn btn-primary form-control" value="提交">
     </div>
  </div>

    </form>


{% endblock %}